# Generated by Django 4.2.7 on 2023-11-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_level_menu_lft_menu_rght_menu_tree_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='nested',
            new_name='parent',
        ),
    ]
