# Generated by Django 4.2.7 on 2023-11-23 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menuitem_delete_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='explicit_url',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem'),
        ),
    ]
