# Generated by Django 4.2.7 on 2023-11-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_menuitem_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='Menu',
        ),
    ]
